[package]
name = "mmb-parser"
version = "0.1.0"
authors = ["Ivo C.S. Wingelaar <ivo@codeforge.rs>"]
description = "A parser for the Metamath Zero binary proof format"
keywords = ["metamath-zero"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
nom = "5"
